-- daily_metrics is fully derived/precomputed (regenerated in full on every
-- refresh-metrics run), unlike establishment/rating data, so a narrow
-- DELETE grant here carries no real data-loss risk. refresh-metrics uses a
-- DELETE-then-INSERT pattern (not INSERT ... ON CONFLICT) specifically
-- because the unique index on (metric_date, scope, local_authority_code)
-- can't reliably catch conflicts for the global-scope row, where
-- local_authority_code is NULL — standard SQL treats NULLs as distinct
-- for uniqueness purposes, so ON CONFLICT would silently insert
-- duplicates rather than update.
-- food_ingestor already exists in production (created during CockroachDB
-- bootstrap, see scripts/bootstrap_cockroachdb.py) — food_migrator only has
-- DDL rights on this database/schema, not the cluster-level CREATEROLE
-- privilege, so this can't create the role itself if missing. For local
-- dev/testing of this migration, create a matching role once manually:
-- `CREATE ROLE food_ingestor;`
GRANT DELETE ON "daily_metrics" TO food_ingestor;
